### ISSUE TITLE
feat: Slow rainbow tags

### ISSUE THREAD

**Issue by Kallecrafter** [Global-Tags/LabyAddon#72]
**As soon as you check the box which is displayed from Supporter/Partner, the tag will now be colored in RGB colors and change color permanently, but not randomly, but like the Rainbow colors of the LabyMod Cosmetics that support Rainbow, so very slowly from yellow to orange, from orange to red and so on.**
**Attention! As soon as you activate the function, you should note that all &1 and &2 &b i.e. all color codes in the GlobalTag are ignored.**

![Unbenannt](https://github.com/user-attachments/assets/32f27746-d1cd-4a09-adbb-9ff87eaced33)

**Comment by RappyTV** [comment]
I already implemented something like this but Nico said it wouldn't be released in the Addon store because there is no way to implement this efficiently.
