### ISSUE TITLE
feat: GlobalTags which change over time

### ISSUE THREAD

**Issue by Kallecrafter** [Global-Tags/LabyAddon#74]
Man kann als Nutzer zwar nur 1 Global Tag festlegen zur Zeit, aber wie wäre es mit Animierten? Damit meine ich nicht das der Text sich animiert sondern Wechselt. Als Partner könnte man beispielsweise 3 GlobalTags festlegen, als Supporter 2, und alle 10 Sekunden würde sich der GlobalTag dann wechseln, von GlobalTag 1 zu GlobalTag 2, 10 Sekunden Später von GlobalTag 2 auf Global Tag 3, weitere 10 von GlobalTag 3 auf GlobalTag 1, und als Supporter würde sich der Zweite zum ersten und andersherum immer wechseln.

**Comment by RappyTV** [comment]
![image](https://github.com/user-attachments/assets/cef35b31-e124-47f3-93e5-eb9ed028b273)
