### ISSUE TITLE
feat: Partner in-game integration.

### ISSUE THREAD

**Issue by Kallecrafter** [Global-Tags/LabyAddon#85]
### Tell us about your concept

A new tab like “leaderboards”.
Partnered servers can be joined.
Partnered streamers can be opened via a link.

![Unbenannt3432](https://github.com/user-attachments/assets/65ade41a-a9e8-4eaa-b045-f5fbf1f1dd67)

**Comment by KubiixD** [comment]
The overall concept and idea is decent, but we're choosing to add hyperlinks on our partner page instead, as implementing a whole menu in-game for partnerships is pretty pointless and far fetched. The hyperlinks will be discussed with partners on a user basis depending on what type of partnership it is. Thank you for the overall idea!
