### ISSUE TITLE
feat: GlobalTags ServerAPI

### ISSUE THREAD

**Issue by Kallecrafter** [Global-Tags/LabyAddon#88]
### Tell us about your concept

A ServerAPI with which you have a Lib, so to speak.

1. You can use the lib to query the tag of a player,
2. You can hide the tag on the respective sub-servers.
3. Global icons for different ranks.

## What ServerAPI users get out of it:

1. By querying the tag, you can, for example, integrate the GlobalTags role into the scoreboard or also into a permission system, which automatically receives the partner rank on the partnered server when a GlobalTags partner.

2. In addition, by hiding tags, for example in mini-games, you can prevent players from being confused by incorrect colours in the tag and provide a certain level of security for the name. Example BedWars: A player takes the tag ‘&9Team Blue’
However, ‘&aTeam Green’ is written under his name
And the player then thinks, oh well, that's a colleague of mine.
(Just as an example)

3. Server global icons for different ranks: You can query which permissions a player has and assign him a global icon, the icons are of course only server-based. Changing the global icon does not change the set image of a player if it already had a global icon before, it is only replaced temporarily, so to speak.

**Comment by RappyTV** [comment]
Thank you for your suggestion and for taking the time to share your concept! While your ideas are interesting, we’ve decided not to pursue this for a few reasons:

1. **Confusion from tags**: It’s usually pretty obvious if everyone has the correct team name under their name and one player has something completely different above.
2. **Scope of GlobalTags**: This feature doesn’t align with the core purpose of the GlobalTags mod. GlobalTags is designed to provide customizable tags and icons for players, not to manage server-based logic or enforce moderation rules for tags and icons.
3. **Moderation of global icons**: Implementing server-global icons would raise significant challenges around moderation. Determining and enforcing what should or shouldn’t appear as a global icon is outside the intended functionality of the mod.

Also take this as a friendly reminder that you don't need to make all of your paragraphs bold. We'll read them regardless of any decorations :)
