### ISSUE TITLE
feat: GlobalTags Partner, Sponsor, Staff Tag (like HDSkins)

### ISSUE THREAD

**Issue by Kallecrafter** [Global-Tags/LabyAddon#91]
### Tell us about your concept

![Unbenannt](https://github.com/user-attachments/assets/7b969ab0-72d7-464a-8702-a50ff66e60ea)
Example for GlobalTags

§9§lGlobalTags §2Staff
§9§lGlobalTags §cPartner
§9§lGlobalTags §6Sponsor

**The tag should always be displayed under the player's name and under the GlobalTag.**

**Comment by RappyTV** [comment]
Hey, first of all I want to thank you for your idea. This won't be implemented as we already have a unique way of displaying roles. I just don't think it would look good to copy the staff tags from LabyMod and HDSkins especially if a player has more than of those tags.
