### ISSUE TITLE
feat: Shortcuts

### ISSUE THREAD

**Issue by Kallecrafter** [Global-Tags/LabyAddon#92]
### Tell us about your concept

Shortcuts in the LabyMod menu under “Control”

You can define the following:

Open GlobalTag Addon menu with a shortcut.

**Comment by RappyTV** [comment]
I don't really see a useful purpose to be honest. A feature like this would most likely not really be used and would rather bloat the settings.

**Comment by RappyTV** [comment]
I don't really see a useful purpose to be honest. A feature like this would most likely not really be used and would rather bloat the settings.
